from google.adk.tools import FunctionTool
from src.task_manager import task_manager, TaskStatus
import json
import subprocess
import os
import asyncio

async def jules_create_task(repository: str, base_branch: str, instruction: str, context_files: list[str] = None) -> dict:
    """
    Creates a new Jules task to run in the local environment based on instructions.
    Returns the task_id.
    """
    if context_files is None:
        context_files = []
    task_id = task_manager.create_task(repository, base_branch, instruction, context_files)

    # Start the async real task execution in the same running loop
    loop = asyncio.get_running_loop()
    loop.create_task(task_manager._run_local_execution(task_id))

    return {"task_id": task_id, "status": "PENDING", "message": "Task successfully created and background execution started."}

def jules_check_status(task_id: str) -> dict:
    """
    Checks the status of an existing Jules task and returns logs.
    """
    task = task_manager.get_task(task_id)
    if not task:
        return {"error_code": "NOT_FOUND", "suggested_action": f"Task ID {task_id} not found."}

    return {
        "task_id": task.task_id,
        "status": task.status,
        "logs": task.logs,
        "created_at": task.created_at.isoformat(),
        "completed_at": task.completed_at.isoformat() if task.completed_at else None,
    }

def jules_get_result(task_id: str, page: int = 1, page_size: int = 1000) -> dict:
    """
    Retrieves the execution result, including truncated diffs.
    Useful for getting diff details without exceeding LLM context windows.
    """
    task = task_manager.get_task(task_id)
    if not task:
        return {"error_code": "NOT_FOUND", "suggested_action": f"Task ID {task_id} not found."}

    if task.status != TaskStatus.PR_READY:
        return {"error_code": "NOT_READY", "suggested_action": "Wait until status is PR_READY before calling jules_get_result."}

    diff = task.diff or ""
    lines = diff.splitlines(keepends=True)

    start_idx = (page - 1) * page_size
    end_idx = min(start_idx + page_size, len(lines))

    truncated_diff = "".join(lines[start_idx:end_idx])
    has_more = end_idx < len(lines)

    # Generate tree structure representation
    tree_process = subprocess.run(["git", "ls-tree", "-r", "--name-only", "HEAD"], cwd=task.repository if os.path.isdir(task.repository) else ".", capture_output=True, text=True)
    tree_stdout = tree_process.stdout.splitlines() if tree_process.stdout else []

    return {
        "task_id": task_id,
        "status": task.status,
        "diff_page": page,
        "diff_preview": truncated_diff,
        "has_more": has_more,
        "file_tree": tree_stdout[:50], # Send up to 50 paths to prevent token explosion
        "message": "Truncated diff provided. Request next page if has_more is true.",
    }

def jules_apply_patch(task_id: str, target_dir: str = ".") -> dict:
    """
    Applies the diff generated by the Jules cloud task onto the local working directory.
    """
    task = task_manager.get_task(task_id)
    if not task:
        return {"error_code": "NOT_FOUND", "suggested_action": f"Task ID {task_id} not found."}

    if task.status != TaskStatus.PR_READY:
        return {"error_code": "NOT_READY", "suggested_action": "Task is not ready to be patched."}

    if not task.diff:
        return {"error_code": "NO_DIFF", "suggested_action": "Task completed without producing a valid diff."}

    patch_file = f"/tmp/{task_id}.patch"
    try:
        with open(patch_file, "w") as f:
            f.write(task.diff)

        # Real code to apply patch using git apply
        result = subprocess.run(["git", "apply", patch_file], cwd=target_dir, capture_output=True, text=True)

        if result.returncode != 0:
            os.remove(patch_file)
            return {
                "error_code": "PATCH_FAILED",
                "suggested_action": "Check local git status, resolve conflicts, or review patch manually.",
                "details": result.stderr
            }

        os.remove(patch_file)
        return {
            "task_id": task_id,
            "status": "APPLIED",
            "message": f"Successfully applied cloud changes to {target_dir} local directory.",
        }
    except Exception as e:
        if os.path.exists(patch_file):
            os.remove(patch_file)
        return {
            "error_code": "PATCH_EXCEPTION",
            "suggested_action": "Exception occurred while trying to apply patch.",
            "details": str(e)
        }

# Expose ADK tools
create_task_tool = FunctionTool(jules_create_task)
check_status_tool = FunctionTool(jules_check_status)
get_result_tool = FunctionTool(jules_get_result)
apply_patch_tool = FunctionTool(jules_apply_patch)

all_adk_tools = [
    create_task_tool,
    check_status_tool,
    get_result_tool,
    apply_patch_tool
]
